"""added new column

Revision ID: 60162b297a20
Revises: 96536e41903d
Create Date: 2023-11-02 18:27:47.535179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60162b297a20'
down_revision = '96536e41903d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
