"""clear

Revision ID: 9137987c4de8
Revises: 
Create Date: 2023-08-04 16:25:53.300031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9137987c4de8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('standard_api_key', sa.String(), nullable=True),
    sa.Column('supplier_external', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nm_id', sa.Integer(), nullable=True),
    sa.Column('subj_name', sa.String(), nullable=True),
    sa.Column('subj_root_name', sa.String(), nullable=True),
    sa.Column('width_cm', sa.Float(), nullable=True),
    sa.Column('length_cm', sa.Float(), nullable=True),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('rv_ten_percents', sa.Float(), nullable=True),
    sa.Column('logistic_box', sa.Float(), nullable=True),
    sa.Column('retail_price', sa.Float(), nullable=True),
    sa.Column('shop_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    op.drop_table('shops')
    # ### end Alembic commands ###
