"""added new column

Revision ID: 96536e41903d
Revises: 9137987c4de8
Create Date: 2023-11-02 13:57:33.530720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96536e41903d'
down_revision = '9137987c4de8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('vendor_code', sa.String(), nullable=True))
    op.add_column('products', sa.Column('brand', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'brand')
    op.drop_column('products', 'vendor_code')
    # ### end Alembic commands ###
